"""Sprint 6: Alembic baseline migration must produce the same schema as init_db.

We don't run actual migrations against the test DB (conftest uses create_all
for speed). This test asserts that the autogenerated baseline migration
matches the current model metadata — the same check ``alembic check`` would
perform — so a clean PostgreSQL deploy via Alembic gets the right schema.
"""

from __future__ import annotations

import importlib.util
import os
from pathlib import Path

from sqlalchemy import create_engine, inspect

# Import init_db package side effects (registers every model on Base.metadata).
from app.db import init_db  # noqa: F401
from app.db.base import Base

BASELINE = Path(__file__).resolve().parents[1] / "alembic" / "versions"


def _load_baseline_module():
    """Handle load baseline module."""
    files = sorted(BASELINE.glob("*_baseline_schema_*.py"))
    assert files, "Expected an Alembic baseline revision in alembic/versions/"
    path = files[0]
    spec = importlib.util.spec_from_file_location("baseline", path)
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)  # type: ignore[union-attr]
    return module


class TestAlembicBaseline:
    """TestAlembicBaseline schema/model definition."""

    def test_baseline_revision_present(self):
        """Test that baseline revision present behaves as expected."""
        module = _load_baseline_module()
        assert module.down_revision is None, "Baseline must be the first revision"
        assert module.revision

    def test_baseline_matches_model_metadata(self, tmp_path):
        """Run the baseline upgrade on a fresh sqlite DB and compare table set."""
        from alembic.config import Config

        from alembic import command

        db_path = tmp_path / "alembic_baseline.db"
        cfg = Config(str(BASELINE.parents[1] / "alembic.ini"))
        cfg.set_main_option("sqlalchemy.url", f"sqlite:///{db_path}")
        cfg.set_main_option("script_location", str(BASELINE.parents[0]))

        # Avoid leaking the parent process's DATABASE_URL into env.py.
        original = os.environ.pop("DATABASE_URL", None)
        try:
            command.upgrade(cfg, "head")
        finally:
            if original is not None:
                os.environ["DATABASE_URL"] = original

        eng = create_engine(f"sqlite:///{db_path}")
        actual = set(inspect(eng).get_table_names()) - {"alembic_version"}
        expected = set(Base.metadata.tables.keys())
        assert actual == expected, f"missing={expected - actual}, extra={actual - expected}"
