"""baseline schema (sprints 1-5)

Revision ID: 9ea2fa322267
Revises: 
Create Date: 2026-05-18 06:24:24.255150

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9ea2fa322267'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action_plan_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('applies_to_level', sa.String(length=20), nullable=False),
    sa.Column('default_tasks', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plan_templates_id'), 'action_plan_templates', ['id'], unique=False)
    op.create_index(op.f('ix_action_plan_templates_tenant_id'), 'action_plan_templates', ['tenant_id'], unique=False)
    op.create_table('backup_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backup_records_created_at'), 'backup_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_backup_records_id'), 'backup_records', ['id'], unique=False)
    op.create_index(op.f('ix_backup_records_tenant_id'), 'backup_records', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('head_user_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['head_user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('portability_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=255), nullable=False),
    sa.Column('subject_email', sa.String(length=255), nullable=False),
    sa.Column('request_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('response_data', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portability_requests_id'), 'portability_requests', ['id'], unique=False)
    op.create_index(op.f('ix_portability_requests_status'), 'portability_requests', ['status'], unique=False)
    op.create_index(op.f('ix_portability_requests_subject_email'), 'portability_requests', ['subject_email'], unique=False)
    op.create_index(op.f('ix_portability_requests_tenant_id'), 'portability_requests', ['tenant_id'], unique=False)
    op.create_table('retention_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('data_category', sa.String(length=100), nullable=False),
    sa.Column('retention_days', sa.Integer(), nullable=False),
    sa.Column('action_on_expiry', sa.String(length=50), nullable=False),
    sa.Column('legal_basis', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_policies_data_category'), 'retention_policies', ['data_category'], unique=False)
    op.create_index(op.f('ix_retention_policies_id'), 'retention_policies', ['id'], unique=False)
    op.create_index(op.f('ix_retention_policies_tenant_id'), 'retention_policies', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ruc', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('sector', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('dpo_name', sa.String(length=255), nullable=True),
    sa.Column('dpo_email', sa.String(length=255), nullable=True),
    sa.Column('dpo_phone', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_id'), 'tenants', ['id'], unique=False)
    op.create_index(op.f('ix_tenants_ruc'), 'tenants', ['ruc'], unique=True)
    op.create_table('training_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_programs_id'), 'training_programs', ['id'], unique=False)
    op.create_index(op.f('ix_training_programs_tenant_id'), 'training_programs', ['tenant_id'], unique=False)
    op.create_table('training_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_modules_id'), 'training_modules', ['id'], unique=False)
    op.create_index(op.f('ix_training_modules_program_id'), 'training_modules', ['program_id'], unique=False)
    op.create_index(op.f('ix_training_modules_tenant_id'), 'training_modules', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Integer(), nullable=True),
    sa.Column('recipient_id', sa.Integer(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_read'), 'alerts', ['is_read'], unique=False)
    op.create_index(op.f('ix_alerts_recipient_id'), 'alerts', ['recipient_id'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_table('arco_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_number', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.String(length=50), nullable=False),
    sa.Column('requester_name', sa.String(length=255), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=False),
    sa.Column('requester_id_number', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('received_date', sa.Date(), nullable=False),
    sa.Column('deadline_date', sa.Date(), nullable=False),
    sa.Column('assigned_dpo_id', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_dpo_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arco_requests_id'), 'arco_requests', ['id'], unique=False)
    op.create_index(op.f('ix_arco_requests_request_type'), 'arco_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_arco_requests_status'), 'arco_requests', ['status'], unique=False)
    op.create_index(op.f('ix_arco_requests_tenant_id'), 'arco_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_arco_requests_ticket_number'), 'arco_requests', ['ticket_number'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('audit_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('auditor_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_plans_id'), 'audit_plans', ['id'], unique=False)
    op.create_index(op.f('ix_audit_plans_status'), 'audit_plans', ['status'], unique=False)
    op.create_index(op.f('ix_audit_plans_tenant_id'), 'audit_plans', ['tenant_id'], unique=False)
    op.create_table('catalog_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sensitivity', sa.String(length=20), nullable=True),
    sa.Column('criticality', sa.String(length=20), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalog_entries_code'), 'catalog_entries', ['code'], unique=False)
    op.create_index(op.f('ix_catalog_entries_criticality'), 'catalog_entries', ['criticality'], unique=False)
    op.create_index(op.f('ix_catalog_entries_id'), 'catalog_entries', ['id'], unique=False)
    op.create_index(op.f('ix_catalog_entries_sensitivity'), 'catalog_entries', ['sensitivity'], unique=False)
    op.create_index(op.f('ix_catalog_entries_tenant_id'), 'catalog_entries', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_catalog_entries_type'), 'catalog_entries', ['type'], unique=False)
    op.create_table('cookie_banners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookie_banners_id'), 'cookie_banners', ['id'], unique=False)
    op.create_index(op.f('ix_cookie_banners_tenant_id'), 'cookie_banners', ['tenant_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['program_id'], ['training_programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_program_id'), 'enrollments', ['program_id'], unique=False)
    op.create_index(op.f('ix_enrollments_tenant_id'), 'enrollments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('incidents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('regulatory_notification_required', sa.Boolean(), nullable=False),
    sa.Column('regulatory_notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('affected_data_types', sa.Text(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_department_id'), 'incidents', ['department_id'], unique=False)
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_status'), 'incidents', ['status'], unique=False)
    op.create_index(op.f('ix_incidents_tenant_id'), 'incidents', ['tenant_id'], unique=False)
    op.create_table('legal_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_documents_doc_type'), 'legal_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_legal_documents_id'), 'legal_documents', ['id'], unique=False)
    op.create_index(op.f('ix_legal_documents_is_current'), 'legal_documents', ['is_current'], unique=False)
    op.create_index(op.f('ix_legal_documents_tenant_id'), 'legal_documents', ['tenant_id'], unique=False)
    op.create_table('retention_execution_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('executed_by_id', sa.Integer(), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('records_exceptions', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('log_details', sa.JSON(), nullable=False),
    sa.Column('run_type', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['executed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['retention_policies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_execution_logs_id'), 'retention_execution_logs', ['id'], unique=False)
    op.create_index(op.f('ix_retention_execution_logs_tenant_id'), 'retention_execution_logs', ['tenant_id'], unique=False)
    op.create_table('training_materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['training_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_materials_id'), 'training_materials', ['id'], unique=False)
    op.create_index(op.f('ix_training_materials_module_id'), 'training_materials', ['module_id'], unique=False)
    op.create_index(op.f('ix_training_materials_tenant_id'), 'training_materials', ['tenant_id'], unique=False)
    op.create_table('treatment_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('legal_basis', sa.String(length=100), nullable=False),
    sa.Column('personal_data_types', sa.JSON(), nullable=False),
    sa.Column('data_subjects', sa.JSON(), nullable=False),
    sa.Column('retention_period_days', sa.Integer(), nullable=False),
    sa.Column('is_cross_border', sa.Boolean(), nullable=False),
    sa.Column('destination_countries', sa.JSON(), nullable=True),
    sa.Column('processor_name', sa.String(length=255), nullable=True),
    sa.Column('processor_country', sa.String(length=100), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_activities_department_id'), 'treatment_activities', ['department_id'], unique=False)
    op.create_index(op.f('ix_treatment_activities_id'), 'treatment_activities', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_activities_tenant_id'), 'treatment_activities', ['tenant_id'], unique=False)
    op.create_table('audit_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audit_plan_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('remediation_notes', sa.Text(), nullable=False),
    sa.Column('remediation_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['audit_plans.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_findings_audit_plan_id'), 'audit_findings', ['audit_plan_id'], unique=False)
    op.create_index(op.f('ix_audit_findings_id'), 'audit_findings', ['id'], unique=False)
    op.create_index(op.f('ix_audit_findings_status'), 'audit_findings', ['status'], unique=False)
    op.create_index(op.f('ix_audit_findings_tenant_id'), 'audit_findings', ['tenant_id'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_activity_id', sa.Integer(), nullable=True),
    sa.Column('data_subject_token', sa.String(length=255), nullable=False),
    sa.Column('legal_basis', sa.String(length=100), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('is_sensitive', sa.Boolean(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revocation_reason', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_activity_id'], ['treatment_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consent_records_data_subject_token'), 'consent_records', ['data_subject_token'], unique=False)
    op.create_index(op.f('ix_consent_records_id'), 'consent_records', ['id'], unique=False)
    op.create_index(op.f('ix_consent_records_is_revoked'), 'consent_records', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_consent_records_tenant_id'), 'consent_records', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_consent_records_treatment_activity_id'), 'consent_records', ['treatment_activity_id'], unique=False)
    op.create_table('cookie_consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('banner_id', sa.Integer(), nullable=False),
    sa.Column('data_subject_token', sa.String(length=255), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['banner_id'], ['cookie_banners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cookie_consents_banner_id'), 'cookie_consents', ['banner_id'], unique=False)
    op.create_index(op.f('ix_cookie_consents_data_subject_token'), 'cookie_consents', ['data_subject_token'], unique=False)
    op.create_index(op.f('ix_cookie_consents_id'), 'cookie_consents', ['id'], unique=False)
    op.create_index(op.f('ix_cookie_consents_tenant_id'), 'cookie_consents', ['tenant_id'], unique=False)
    op.create_table('dpia_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_activity_id', sa.Integer(), nullable=False),
    sa.Column('step1_description', sa.Text(), nullable=False),
    sa.Column('step2_risk_analysis', sa.Text(), nullable=False),
    sa.Column('step3_mitigations', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('signed_by_id', sa.Integer(), nullable=True),
    sa.Column('pdf_bytes', sa.LargeBinary(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['signed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_activity_id'], ['treatment_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dpia_assessments_id'), 'dpia_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_dpia_assessments_status'), 'dpia_assessments', ['status'], unique=False)
    op.create_index(op.f('ix_dpia_assessments_tenant_id'), 'dpia_assessments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_dpia_assessments_treatment_activity_id'), 'dpia_assessments', ['treatment_activity_id'], unique=False)
    op.create_table('information_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('asset_type_code', sa.String(length=100), nullable=False),
    sa.Column('format_code', sa.String(length=100), nullable=False),
    sa.Column('storage_medium_code', sa.String(length=100), nullable=False),
    sa.Column('classification_level_code', sa.String(length=100), nullable=False),
    sa.Column('treatment_activity_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_activity_id'], ['treatment_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_information_assets_department_id'), 'information_assets', ['department_id'], unique=False)
    op.create_index(op.f('ix_information_assets_id'), 'information_assets', ['id'], unique=False)
    op.create_index(op.f('ix_information_assets_tenant_id'), 'information_assets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_information_assets_treatment_activity_id'), 'information_assets', ['treatment_activity_id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('treatment_activity_id', sa.Integer(), nullable=False),
    sa.Column('analyst_id', sa.Integer(), nullable=True),
    sa.Column('responses', sa.JSON(), nullable=False),
    sa.Column('probability', sa.Integer(), nullable=False),
    sa.Column('impact', sa.Integer(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['analyst_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['treatment_activity_id'], ['treatment_activities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_tenant_id'), 'risk_assessments', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_treatment_activity_id'), 'risk_assessments', ['treatment_activity_id'], unique=False)
    op.create_table('action_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=True),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tasks', sa.JSON(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('auto_generated', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['action_plan_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_action_plans_id'), 'action_plans', ['id'], unique=False)
    op.create_index(op.f('ix_action_plans_risk_assessment_id'), 'action_plans', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_action_plans_status'), 'action_plans', ['status'], unique=False)
    op.create_index(op.f('ix_action_plans_tenant_id'), 'action_plans', ['tenant_id'], unique=False)
    op.create_table('remediations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('responsible_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('risk_score_before', sa.Integer(), nullable=True),
    sa.Column('risk_score_after', sa.Integer(), nullable=True),
    sa.Column('risk_level_before', sa.String(length=20), nullable=True),
    sa.Column('risk_level_after', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['responsible_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediations_id'), 'remediations', ['id'], unique=False)
    op.create_index(op.f('ix_remediations_risk_assessment_id'), 'remediations', ['risk_assessment_id'], unique=False)
    op.create_index(op.f('ix_remediations_status'), 'remediations', ['status'], unique=False)
    op.create_index(op.f('ix_remediations_tenant_id'), 'remediations', ['tenant_id'], unique=False)
    op.create_table('retention_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('information_asset_id', sa.Integer(), nullable=False),
    sa.Column('policy_id', sa.Integer(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('legal_hold', sa.Boolean(), nullable=False),
    sa.Column('hold_justification', sa.Text(), nullable=False),
    sa.Column('review_decision', sa.String(length=50), nullable=True),
    sa.Column('decision_rationale', sa.Text(), nullable=False),
    sa.Column('reviewed_by_id', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['information_asset_id'], ['information_assets.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['retention_policies.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_retention_records_id'), 'retention_records', ['id'], unique=False)
    op.create_index(op.f('ix_retention_records_information_asset_id'), 'retention_records', ['information_asset_id'], unique=False)
    op.create_index(op.f('ix_retention_records_status'), 'retention_records', ['status'], unique=False)
    op.create_index(op.f('ix_retention_records_tenant_id'), 'retention_records', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_retention_records_tenant_id'), table_name='retention_records')
    op.drop_index(op.f('ix_retention_records_status'), table_name='retention_records')
    op.drop_index(op.f('ix_retention_records_information_asset_id'), table_name='retention_records')
    op.drop_index(op.f('ix_retention_records_id'), table_name='retention_records')
    op.drop_table('retention_records')
    op.drop_index(op.f('ix_remediations_tenant_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_status'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_risk_assessment_id'), table_name='remediations')
    op.drop_index(op.f('ix_remediations_id'), table_name='remediations')
    op.drop_table('remediations')
    op.drop_index(op.f('ix_action_plans_tenant_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_status'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_risk_assessment_id'), table_name='action_plans')
    op.drop_index(op.f('ix_action_plans_id'), table_name='action_plans')
    op.drop_table('action_plans')
    op.drop_index(op.f('ix_risk_assessments_treatment_activity_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_tenant_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_information_assets_treatment_activity_id'), table_name='information_assets')
    op.drop_index(op.f('ix_information_assets_tenant_id'), table_name='information_assets')
    op.drop_index(op.f('ix_information_assets_id'), table_name='information_assets')
    op.drop_index(op.f('ix_information_assets_department_id'), table_name='information_assets')
    op.drop_table('information_assets')
    op.drop_index(op.f('ix_dpia_assessments_treatment_activity_id'), table_name='dpia_assessments')
    op.drop_index(op.f('ix_dpia_assessments_tenant_id'), table_name='dpia_assessments')
    op.drop_index(op.f('ix_dpia_assessments_status'), table_name='dpia_assessments')
    op.drop_index(op.f('ix_dpia_assessments_id'), table_name='dpia_assessments')
    op.drop_table('dpia_assessments')
    op.drop_index(op.f('ix_cookie_consents_tenant_id'), table_name='cookie_consents')
    op.drop_index(op.f('ix_cookie_consents_id'), table_name='cookie_consents')
    op.drop_index(op.f('ix_cookie_consents_data_subject_token'), table_name='cookie_consents')
    op.drop_index(op.f('ix_cookie_consents_banner_id'), table_name='cookie_consents')
    op.drop_table('cookie_consents')
    op.drop_index(op.f('ix_consent_records_treatment_activity_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_tenant_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_is_revoked'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_id'), table_name='consent_records')
    op.drop_index(op.f('ix_consent_records_data_subject_token'), table_name='consent_records')
    op.drop_table('consent_records')
    op.drop_index(op.f('ix_audit_findings_tenant_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_status'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_id'), table_name='audit_findings')
    op.drop_index(op.f('ix_audit_findings_audit_plan_id'), table_name='audit_findings')
    op.drop_table('audit_findings')
    op.drop_index(op.f('ix_treatment_activities_tenant_id'), table_name='treatment_activities')
    op.drop_index(op.f('ix_treatment_activities_id'), table_name='treatment_activities')
    op.drop_index(op.f('ix_treatment_activities_department_id'), table_name='treatment_activities')
    op.drop_table('treatment_activities')
    op.drop_index(op.f('ix_training_materials_tenant_id'), table_name='training_materials')
    op.drop_index(op.f('ix_training_materials_module_id'), table_name='training_materials')
    op.drop_index(op.f('ix_training_materials_id'), table_name='training_materials')
    op.drop_table('training_materials')
    op.drop_index(op.f('ix_retention_execution_logs_tenant_id'), table_name='retention_execution_logs')
    op.drop_index(op.f('ix_retention_execution_logs_id'), table_name='retention_execution_logs')
    op.drop_table('retention_execution_logs')
    op.drop_index(op.f('ix_legal_documents_tenant_id'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_is_current'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_id'), table_name='legal_documents')
    op.drop_index(op.f('ix_legal_documents_doc_type'), table_name='legal_documents')
    op.drop_table('legal_documents')
    op.drop_index(op.f('ix_incidents_tenant_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_status'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_department_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_tenant_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_program_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_cookie_banners_tenant_id'), table_name='cookie_banners')
    op.drop_index(op.f('ix_cookie_banners_id'), table_name='cookie_banners')
    op.drop_table('cookie_banners')
    op.drop_index(op.f('ix_catalog_entries_type'), table_name='catalog_entries')
    op.drop_index(op.f('ix_catalog_entries_tenant_id'), table_name='catalog_entries')
    op.drop_index(op.f('ix_catalog_entries_sensitivity'), table_name='catalog_entries')
    op.drop_index(op.f('ix_catalog_entries_id'), table_name='catalog_entries')
    op.drop_index(op.f('ix_catalog_entries_criticality'), table_name='catalog_entries')
    op.drop_index(op.f('ix_catalog_entries_code'), table_name='catalog_entries')
    op.drop_table('catalog_entries')
    op.drop_index(op.f('ix_audit_plans_tenant_id'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_status'), table_name='audit_plans')
    op.drop_index(op.f('ix_audit_plans_id'), table_name='audit_plans')
    op.drop_table('audit_plans')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_arco_requests_ticket_number'), table_name='arco_requests')
    op.drop_index(op.f('ix_arco_requests_tenant_id'), table_name='arco_requests')
    op.drop_index(op.f('ix_arco_requests_status'), table_name='arco_requests')
    op.drop_index(op.f('ix_arco_requests_request_type'), table_name='arco_requests')
    op.drop_index(op.f('ix_arco_requests_id'), table_name='arco_requests')
    op.drop_table('arco_requests')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_recipient_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_is_read'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_training_modules_tenant_id'), table_name='training_modules')
    op.drop_index(op.f('ix_training_modules_program_id'), table_name='training_modules')
    op.drop_index(op.f('ix_training_modules_id'), table_name='training_modules')
    op.drop_table('training_modules')
    op.drop_index(op.f('ix_training_programs_tenant_id'), table_name='training_programs')
    op.drop_index(op.f('ix_training_programs_id'), table_name='training_programs')
    op.drop_table('training_programs')
    op.drop_index(op.f('ix_tenants_ruc'), table_name='tenants')
    op.drop_index(op.f('ix_tenants_id'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_retention_policies_tenant_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_id'), table_name='retention_policies')
    op.drop_index(op.f('ix_retention_policies_data_category'), table_name='retention_policies')
    op.drop_table('retention_policies')
    op.drop_index(op.f('ix_portability_requests_tenant_id'), table_name='portability_requests')
    op.drop_index(op.f('ix_portability_requests_subject_email'), table_name='portability_requests')
    op.drop_index(op.f('ix_portability_requests_status'), table_name='portability_requests')
    op.drop_index(op.f('ix_portability_requests_id'), table_name='portability_requests')
    op.drop_table('portability_requests')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_backup_records_tenant_id'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_id'), table_name='backup_records')
    op.drop_index(op.f('ix_backup_records_created_at'), table_name='backup_records')
    op.drop_table('backup_records')
    op.drop_index(op.f('ix_action_plan_templates_tenant_id'), table_name='action_plan_templates')
    op.drop_index(op.f('ix_action_plan_templates_id'), table_name='action_plan_templates')
    op.drop_table('action_plan_templates')
    # ### end Alembic commands ###
